services:
  - type: web
    name: image-forensics-app
    env: python
    buildCommand: |
      apt-get update && apt-get install -y tesseract-ocr
      pip install -r requirements.txt
    startCommand: gunicorn main:app --bind 0.0.0.0:8000
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: CELERY_BROKER_URL
        value: redis://image-forensics-redis:6379/0
      - key: CELERY_RESULT_BACKEND
        value: redis://image-forensics-redis:6379/0

  - type: worker
    name: image-forensics-worker
    env: python
    buildCommand: |
      apt-get update && apt-get install -y tesseract-ocr
      pip install -r requirements.txt
    startCommand: celery -A celery_worker.celery worker --loglevel=info
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: CELERY_BROKER_URL
        value: redis://image-forensics-redis:6379/0
      - key: CELERY_RESULT_BACKEND
        value: redis://image-forensics-redis:6379/0

  - type: redis
    name: image-forensics-redis
    ipAllowList: []
