services:
  - type: web
    name: image-forensics-app
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: CELERY_BROKER_URL
        value: redis://red-cvfcd2popnds73b8snfg:6379/0
      - key: CELERY_RESULT_BACKEND
        value: redis://red-cvfcd2popnds73b8snfg:6379/0

  - type: worker
    name: image-forensics-worker
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: CELERY_BROKER_URL
        value: redis://red-cvfcd2popnds73b8snfg:6379/0
      - key: CELERY_RESULT_BACKEND
        value: redis://red-cvfcd2popnds73b8snfg:6379/0

  - type: redis
    name: image-forensics-redis
    ipAllowList: []
